/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
function feses_rutin() {		

    var tableRef = document.getElementById('table_nya').getElementsByTagName('tbody')[0];
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
    var newText = document.createTextNode('feses rutin');
    var newText1 = document.createTextNode('makroskopis');
    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses rutin');
    var newText1 = document.createTextNode('warna');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "warna_feses");
    var newText3 = document.createTextNode('cokelat muda - cokelat ');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses rutin');
    var newText1 = document.createTextNode('bau');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "bau_feses");
    var newText3 = document.createTextNode('khas');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses rutin');
    var newText1 = document.createTextNode('konsistensi');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "konsistensi");
    var newText3 = document.createTextNode('lembek');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses rutin');
    var newText1 = document.createTextNode('lendir');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "lendir");
    var newText3 = document.createTextNode('negatif');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses rutin');
    var newText1 = document.createTextNode('darah');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "darah");
    var newText3 = document.createTextNode('negatif');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses rutin');
    var newText1 = document.createTextNode('ph');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "ph_feses");
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell4.appendChild(newText4);
}
function feses_lengkap() {
    var tableRef = document.getElementById('table_nya').getElementsByTagName('tbody')[0];
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('makroskopis');
    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('warna');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "warna_feses");
    var newText3 = document.createTextNode('cokelat muda - cokelat ');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('bau');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "bau_feses");
    var newText3 = document.createTextNode('khas');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('konsistensi');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "konsistensi");
    var newText3 = document.createTextNode('lembek');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('lendir');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "lendir");
    var newText3 = document.createTextNode('negatif');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('darah');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "darah");
    var newText3 = document.createTextNode('negatif');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('ph');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "ph_feses");
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell4.appendChild(newText4);
    
    
    
    
    
    
//    micro
var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('mikroskopis');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('eritrosit');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "eritrosit");
    var newText3 = document.createTextNode('negatif');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('lekosit');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "lekosit_feses");
    var newText3 = document.createTextNode('negatif');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('amoeba');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "amoeba");
    var newText3 = document.createTextNode('negatif');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('parasit/telor cacing');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "parasit_telur_cacing");
    var newText3 = document.createTextNode('negatif');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('sisa makanan');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "sisa_makanan");
//    var newText3 = document.createTextNode('negatif');
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
//    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('lemak');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "lemak");
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell4.appendChild(newText4);
    
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
//    var newText = document.createTextNode('feses lengkap');
    var newText1 = document.createTextNode('lain-lain');
    var newText2 = document.createElement('input');
    newText2.setAttribute("id", "lain_lain_feses");
    var newText4 = document.createElement('input');
//    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell4.appendChild(newText4);
}
function darah_samar() {
    var tableRef = document.getElementById('table_nya').getElementsByTagName('tbody')[0];
    var newRow = tableRef.insertRow(tableRef.rows.length);
    var newCell = newRow.insertCell(0);
    var newCell1 = newRow.insertCell(1);
    var newCell2 = newRow.insertCell(2);
    var newCell3 = newRow.insertCell(3);
    var newCell4 = newRow.insertCell(4);
    var newText = document.createTextNode('darah samar');
    var newText1 = document.createTextNode('darah samar');
    var newText2 = document.createElement('input');
    newText2.setAttribute("type", "text");
    newText2.setAttribute("id", "darah_samar");
    var newText3 = document.createTextNode('negatif');
    var newText4 = document.createElement('input');

    newCell.appendChild(newText);
    newCell1.appendChild(newText1);
    newCell2.appendChild(newText2);
    newCell3.appendChild(newText3);
    newCell4.appendChild(newText4);
}
